# static definitions of dashboard items
#
# Each item represents entry on dashboard.
# set to 'items: []' for empty list.
items:

    - # item title
      name: Duck Duck Go

      # name by which elements are aggregated
      namespace: searching

      # URL to which the element links to
      url: "https://duckduckgo.com/"

    - name: Bing
      namespace: searching
      url: "https://www.bing.com/"

    - name: Google
      namespace: searching
      url: "https://www.google.com/"

    - name: X
      namespace: social
      url: "https://x.com/"

    - name: Reddit
      namespace: social
      url: "https://www.reddit.com/"

    - name: XKCD
      namespace: timekill
      url: "https://xkcd.com/"
      icon: "https://xkcd.com/s/0b7742.png"

    - name: 9gag
      namespace: timekill
      url: "https://9gag.com/"

    - name: boredpanda
      namespace: timekill
      url: "https://www.boredpanda.com/"
